### ISSUE TITLE
An experiment on ImageNet 1K

### ISSUE THREAD

**Issue by lteyoungjun** [kaist-dmlab/MQNet#5]
Hello author, 
Thanks for the release of the code of your paper.

For ImageNet 1K, you used 50 classes as ID and other 950 classes as OOD.
If you don't mind, could you perform other options such as (ID: 100, OOD:900 or ID: 500, OOD:500)?

Thank you in advance! ^_^

**Comment by dongmean** [comment]
Thank you for your comment. 
You can perform various experiments on _any_ IN-OOD split ratio setups.
All you need is to simply adjusting [load_split_data.py](https://github.com/kaist-dmlab/MQNet/blob/main/load_split_data.py).
