### ISSUE TITLE
 About the justifications for using certain epochs. 

### ISSUE THREAD

**Issue by rooknpown** [kaist-dmlab/MQNet#6]
For the provided code, 
--epochs 200 --epochs-csi 1000 --epochs-mqnet 100
how are these numbers set?

**Comment by dongmean** [comment]
Thank you for the question.
For CSI, we follow the setup of the original paper.
For backbone classifier, we follow the setup of existing AL studies.
For MQNet, we set it to 100 and empirically found that it works well to various datasets.
